export * from './button/button.component';
export * from './decorative-bubbles/decorative-bubbles.component';
export * from './main-contact-form/main-contact-form.component';
export * from './services-box/services-box.component';
export * from './skills-box/skills-box.component';
export * from './social-box/social-box.component';
export * from './svg/svg.component';
export * from './fade-in-animation/fade-in-animation.component';
export * from './iubenda-banner/iubenda-banner.component'
export * from './open-graph/open-graph.component'