export * from './customers-section/customers-section.component'
export * from './footer-section/footer-section.component'
export * from './header-section/header-section.component'
export * from './presentation-section/presentation-section.component'
export * from './skills-section/skills-section.component'
export * from './footer-section/footer-section.component'
export * from './last-articles-section/last-articles.section'
